package version

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type Info struct {
	GoVersion      string `json:"go_version,omitempty"`
	Platform       string `json:"platform,omitempty"`
	CommitHash     string `json:"commit_hash,omitempty"`
	CommitterName  string `json:"committer_name,omitempty"`
	CommitterEmail string `json:"committer_email,omitempty"`
	CommitterDate  string `json:"committer_date,omitempty"`
}

func (i Info) String() string {
	marshal, err := json.MarshalIndent(i, "", "\t")
	if err != nil {
		panic(err)
	}
	return string(marshal)
}

func (i Info) MakeBuildCfg() {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by auto build version; DO NOT EDIT.\n")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "const ")
}
